---
title: "test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r persp, fig.show = "hold", warning=FALSE, message=FALSE, out.width= '50%'}
z_min <- min(data$auc) - c(min(data$auc) * 0.02)
z_max <- max(data$auc) + c(max(data$auc) * 0.02)

# use a viridis palette for usability
library(viridis)
color <- plasma(256)

par(mar = c(1, 1, 2, 0),
    mfrow = c(3, 3),
    cex = 0.4)

par_cut <- data.frame(
  t = c(rep(0, 6), -3, 0,+3),
  rh = c(rep(0, 3), -3, 0,+3, rep(0, 3)),
  h = c(-3, 0,+3, rep(0, 6))
)

plot_ls <- list()

for (i in seq(nrow(par_cut))) {
  persp(poly_3_fit,
        if (i <= 3) {
          ~ rh + t
        } else if (i %in% 4:6) {
          ~ h + t
        } else if (i >= 7) {
          ~ h + rh
        }
        ,
        at = data.frame(par_cut[i,]),
    zlab = "\n\nAUROC",
    col = color,
    zlim = c(z_min, z_max),
    theta = 60,
    phi = 15,
    border = "grey15",
    lwd = 0.5,
    cex.main = 1.2,
    # cex.axis = 1.3,
    cex.lab = 1.1,
    main = paste0(letters[i],") ", "Response at ", 
                  "t = ", par_cut[i,1] + 10, "; ", 
                  "rh = ", par_cut[i,2] + 90, "; ", 
                  "h = ", par_cut[i,3] +10)
  )
}
```
