% About

This repository is part of results of my PhD project. Here I present the evaluation of the potato late blight forecasting model used in Republic of Ireland, called Irish Rules. 

The funding for this project comes from [DAFM (Department of Agriculture, Food and Marine)](https://www.agriculture.gov.ie). 

## Notes 

Some code chunks are folded and they can be accessed by clicking on the arrow (The code).  
Try not to have other R sessions running because it could produce problems installing libraries.  
If there are any problems reproducing the analysis, please raise an issue on GitHub.  

## Project team

Maynooth University:
- [Rowan Fealy](https://www.maynoothuniversity.ie/people/rowan-fealy)

Teagasc:
- [Stephen Kildea](https://www.teagasc.ie/contact/staff-directory/k/steven-kildea/)

Met Eirean:
- [Keith Lambkin](https://www.researchgate.net/profile/Keith_Lambkin)

University of Southern Queensland:
- [Adam Sparks](https://adamhsparks.netlify.com/)


## Citation

Please cite this research compendium as:


> Cucak, M., Sparks, A., Fealy, R., Lambkin, K., and Kildea, S. 2019. Evaluation of the Irish Rules, a potato late blight forecasting used in Ireland. 

## Licences

Data: [CC-0](https://creativecommons.org/publicdomain/zero/1.0/) attribution requested in reuse
Manuscript: [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/)  
Code: [MIT](https://opensource.org/licenses/MIT) year: 2019, copyright holder: Mladen Cucak

## Contributions

We welcome contributions from everyone. Before you get started, please see our [contributor guidelines](CONTRIBUTING.html). Please note that this project is released with a [Contributor Code of Conduct](CONDUCT.html). By participating in this project you agree to abide by its terms.

